apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: kustomize-example
spec:
  project: default
  source:
    repoURL: 'https://github.com/iraklikairakli/kustomize-applicationste.git'
    targetRevision: HEAD
    path: 'overlays/dev'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true